version: "3.7"
services:
  autohooks-plugin-ruff:
    container_name: ${DOCKER_CONTAINER_NAME}
    hostname: ${DOCKER_CONTAINER_NAME}
    restart: always
    image: ${REGISTRY}:${REGISTRY_PORT}/${DOCKER_CONTAINER_NAME}_image
    env_file:
      - .env
    volumes:
      - ./:/src/
    logging:
      driver: 'json-file'
      options:
        max-size: 50m
        max-file: '2'